### ISSUE TITLE
צבע מבצבץ

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#87] opened 2018-04-29 11:09 UTC
שאריות צבע מבצבצות מתחת לטקסט

![image](https://user-images.githubusercontent.com/8996235/39405904-ea82464c-4bb6-11e8-9563-d8888bb451de.png)

**Comment by maryLoi** [comment] 2018-04-29 11:10
![image](https://user-images.githubusercontent.com/8996235/39405916-1f505d3c-4bb7-11e8-8383-3b8419724c6b.png)

**Comment by maryLoi** [comment] 2018-04-29 11:15
![image](https://user-images.githubusercontent.com/8996235/39405960-bee61bf2-4bb7-11e8-854f-d81ea3f9641f.png)

**Comment by akariv** [comment] 2018-08-05 08:13
Duplicate of https://github.com/OpenBudget/mushonkey/issues/4

**Closed by akariv** 2018-08-05 08:13 UTC
