### ISSUE TITLE
company page description (add missing word)

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#196] opened 2018-07-30 15:06 UTC
missing the word "חברה":

http://next.obudget.org/i/org/company/510728777?li=0

![image](https://user-images.githubusercontent.com/3581741/43405773-47f9ef8c-9423-11e8-84e7-936fbdac717a.png)

**Comment by akariv** [comment] 2018-08-05 06:59
Duplicate of https://github.com/OpenBudget/BudgetKey/issues/139

**Closed by akariv** 2018-08-05 06:59 UTC
Labels: users feedback
