### ISSUE TITLE
search results: fix governmental decisions and names basic card style

### ISSUE THREAD

**Issue by noamoss** [OpenBudget/BudgetKey#298] opened 2018-12-31 10:31 UTC
1. weird strip at the top of the result elements cards 
2. Cards are not in full height

![image](https://user-images.githubusercontent.com/3581741/50558544-f77b0200-0cf7-11e9-9f26-a2af620c015b.png)

https://next.obudget.org/s/?q=%D7%A4%D7%99%D7%A8%D7%95%D7%AA&dd=all&range=last_month&lang=he

**Comment by akariv** [comment] 2018-12-31 10:46
This is part of the search result design, naturally.
Duplicate of #295

**Closed by akariv** 2018-12-31 10:47 UTC
Labels: prioritised
